### ISSUE TITLE
Does it work offline?

### ISSUE THREAD

**Issue by iilyak** [frederikheld/usm.io#52]
From the description in the README.md it is not clear whether the tools works offline or using an online service on Internet. It would be nice to add this information to the README.md

**Comment by frederikheld** [comment]
Hey @iilyak,

I'm sorry for having you wait so long.

The package itself is designed to be integrated into your own project and run in a build pipeline along with your source code with the results hosted on a webserver.

However, the package also comes with an [exampe](https://github.com/frederikheld/usm.io/tree/master/example) that shows how you can use the package in your own project. It works out of the box and you can open the generated websites locally in your web browser without the need for hosting.

To answer your yestion: yes, it works offline as well.

I've made some changes to the docs which hopefully make it clearer that the example is the best place to start undertanding how to use _usm.io_. But I have to admit that I'm quite limited in my ability to explain the whole thing in simple terms as I have worked too long on this project, so for me everything is very clear :-D

If you have any more suggestions what needs to be more clear, just give me a hint!

Cheers,
Fred

**Comment by iilyak** [comment]
Thank you.
